name: Greetings

on:
  issue_comment:
    types: [created]

jobs:
  greeting:
    if: contains(github.event.comment.body, '/noti')
    runs-on: ubuntu-latest
    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.issue.node_id }}
        response: "Well Done !! Thank you @${{ github.event.comment.user.login }} for your contribution :)"
        author: ${{ github.event.comment.user.login }}
