name: test

on:
  push:
    branches: [ chore/**, feature/**, bug/**]

jobs:
        
  Test:
    name: Test
    runs-on: macos-11
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
            
    - name: Bundle install
      run: bundle install

    - name: Cache SPM
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Test Build
      run: bundle exec fastlane scan_build